### PR TITLE
Guidance for Artifact Evaluation

### PR DESCRIPTION
**Pull request by madelonhulsebos**
Include guidance and a reference (as provided by Eric Eide) for the artifact evaluation to the cfp page of the jsys website.
The part "this document" refers to the following link: [http://bit.ly/HOWTO-AEC](http://bit.ly/HOWTO-AEC).

Screenshot 2022-09-27 at 20 18 06

### CODE REVIEW

**Comment by romain-jacob** [comment]
Thanks @madelonhulsebos ! Two comments: 

- I'd not use the link shortener, since we anyway do not display the URL (and some people don't like bit.ly)
- Any reason why you did not include the second link, with the blog post? 

I see that you chose to keep only the middle part, I think that makes sense on the cfp page. I would however retain the rest of Eric's info though, as I think it's really important to understand the expectations from our side. Most likely, that should live in a dedicated page. Could you take a stab at that? 

The idea would be to create a new file in the `/pages` folder (alike the paper types ones) and link to it from the CfP pages with something like "For more details, about the AE, read this page"

(this should also be linked to from the yet-unexisting "instruction for authors" page, but one thing at a time...)

**Comment by madelonhulsebos** [comment]
@romain-jacob there is now a separate page linked from the CfP with the content from Eric Eide's email and both references. This separate page includes all information regarding AE as on the CfP page as well (for completeness). Below the result.

Screenshot 2022-09-28 at 21 00 06

Screenshot 2022-09-28 at 21 00 34

**Comment by romain-jacob** [comment]
Thanks a lot! 

One more point: I am pondering whether we want to have the AE page directly on the main menu... I'm not sure tbh. Possibly, I actually like the idea to emphasize that we do AE. I'm not sure tbh. Okay, let's do it :-) 

But if we do, it should not be placed at the end. A more natural placing would be between `Editorial board` and `Stats` I suppose. 

The only way I found to manage this is with file naming (gotta be some other way but...). That's why the page with a "menutitle" metadata have a `X_` at the start of their name. So here, the AE page should be renamed `04_xyz` and the stat page renamed `05_stats`.

**Comment by madelonhulsebos** [comment]
That was my first setup as well, until I read your message better and changed back. The page is now added in the header!

**Pull request merged**
